spring.application.name=ecom

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:h2ecom

product.image=images/

#spring.jpa.hibernate.ddl-auto=update

spring.app.jwtSecret=q9vY3tL8m2R5s7H1k4P6w8Z0x3C9n5B2d7F1a6M8j2K4r9T5u1V7y0N3p6Q8z5

spring.app.jwtExpirationMs=3000000

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.ecommerce.ecom=DEBUG